name: Deploy to Stellar

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ secrets.STELLAR_HOST }}
          port: ${{ secrets.STELLAR_PORT }}
          username: ${{ secrets.STELLAR_USERNAME }}
          password: ${{ secrets.STELLAR_PASSWORD }}
          localDir: ./
          remoteDir: /public_html
          syncDelete: true
